### ISSUE TITLE
Migrate to newest (stable) version of the STM32 cube

### ISSUE THREAD

**Issue by Kai2c** [DeverSean/lamppedal#4]
I get a warning when I open the `.ioc` to launch the device configuration GUI (Newest I have installed is 6.10). 

Warning: 
<img width="411" alt="image" src="https://github.com/DeverSean/lamppedal/assets/49332438/039bab77-af72-4a51-9c6c-2ff90466f505">

**Comment by DeverSean** [comment]
I updated my IDE to the newest version (1.14.1) and migrated the project. Let's use 1.14.1 for this project, and migrate again if necessary.
